Repository SU-SWS/stanford_media, pull requests merged in 2020-11, with the labels that each got.

#74 "8.x-2.x 8.2.10
  CHANGELOG.md
  modules/media_duplicate_validation/media_duplicate_validation.info.yml
  modules/media_duplicate_validation/src/Plugin/MediaDuplicateValidation/ColorMean.php
  src/Plugin/Field/FieldFormatter/EmbeddableFormatter.php
  stanford_media.info.yml
Labels: backend, patch, size/xs

#76 D8CORE-2428 Patch drupal core for media library validation
  CHANGELOG.md
  composer.json
  modules/media_duplicate_validation/media_duplicate_validation.info.yml
  stanford_media.info.yml
Labels: patch, size/xs

#78 D9 Ready
  composer.json
  stanford_media.info.yml
Labels: patch, size/xs

#80 D8CORE-2753: convert to webpack and caption edits.
  Gruntfile.js
  README.md
  css/stanford_media.admin.css
  css/stanford_media.css
  dist/assets/img/drupalimage.png
  dist/css/stanford_media.admin.css
  dist/css/stanford_media.css
  lib/img/drupalimage.png
  lib/scss/stanford_media.admin.scss
  lib/scss/stanford_media.scss
  package-lock.json
  package.json
  scss/stanford_media.scss
  stanford_media.libraries.yml
  webpack.config.js
Labels: frontend, size/xl

#79 Adjusted tests to pass on D9
  tests/src/Kernel/Plugin/Filter/MediaEmbedMarkupFilterTest.php
  tests/src/Unit/Plugin/BundleSuggestion/BundleSuggestionTestBase.php
  tests/src/Unit/Plugin/Validation/Constraint/GoogleFormsConstraintValidatorTest.php
Labels: backend, size/xs, tests

#82 D8CORE-2267 Removed caption checkbox from file media
  src/Plugin/MediaEmbedDialog/File.php
Labels: backend, size/xs
