Repository SU-SWS/stanford_media, pull requests merged in 2021-03, with the labels that each got.

#90 Updated linkit module
  composer.json
Labels: size/xs

#91 "8.x-2.x 8.2.14
  CHANGELOG.md
  composer.json
  modules/media_duplicate_validation/media_duplicate_validation.info.yml
  stanford_media.info.yml
Labels: patch, size/xs

#92 Provide a message on media form and lock default field media items
  stanford_media.module
  stanford_media.permissions.yml
Labels: backend, size/xs
