Repository SU-SWS/stanford_media, pull requests merged in 2023-10, with the labels that each got.

#139 HSD8 1416
  src/Controller/MediaUsageController.php
  src/EventSubscriber/StanfordMediaSubscriber.php
  src/Plugin/views/field/EntityUsageLink.php
  stanford_media.links.task.yml
  stanford_media.module
  stanford_media.routing.yml
  stanford_media.services.yml
  tests/src/Kernel/Plugin/views/field/EntityUsageLinkTest.php
Labels: backend, tests, size/s

#142 D8CORE-6976: removed the italics on the caption
  dist/css/stanford_media.css
  scss/stanford_media.scss
Labels: size/xs, frontend

#143 10.1.0
  CHANGELOG.md
  stanford_media.info.yml
Labels: minor, size/xs
